# Generated by Django 2.1.7 on 2019-04-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0002_auto_20190425_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='upload',
            field=models.ImageField(default='static/img/user.png', upload_to='static/media/images/user-avatar'),
        ),
    ]
