# Generated by Django 2.1.7 on 2019-05-14 16:56

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0005_remove_question_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/img/user.png', upload_to='uploads/%Y/%m/%d/%H', verbose_name='Avatar'),
        ),
    ]
